// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace RaceDay.Controllers
{
    public partial class AuthorizeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AuthorizeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AuthorizeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RedirectToActionWithMessage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RedirectToActionWithMessage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AjaxRedirect()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRedirect);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AuthorizeController Actions { get { return MVC.Authorize; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Authorize";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Authorize";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string FBApp = "FBApp";
            public readonly string Logon = "Logon";
            public readonly string RedirectToActionWithMessage = "RedirectToActionWithMessage";
            public readonly string AjaxRedirect = "AjaxRedirect";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string FBApp = "FBApp";
            public const string Logon = "Logon";
            public const string RedirectToActionWithMessage = "RedirectToActionWithMessage";
            public const string AjaxRedirect = "AjaxRedirect";
        }


        static readonly ActionParamsClass_RedirectToActionWithMessage s_params_RedirectToActionWithMessage = new ActionParamsClass_RedirectToActionWithMessage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RedirectToActionWithMessage RedirectToActionWithMessageParams { get { return s_params_RedirectToActionWithMessage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RedirectToActionWithMessage
        {
            public readonly string redirectAction = "redirectAction";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AjaxRedirect s_params_AjaxRedirect = new ActionParamsClass_AjaxRedirect();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AjaxRedirect AjaxRedirectParams { get { return s_params_AjaxRedirect; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AjaxRedirect
        {
            public readonly string redirectAction = "redirectAction";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Denied = "Denied";
                public readonly string Error = "Error";
                public readonly string FBApp = "FBApp";
                public readonly string Logon = "Logon";
            }
            public readonly string Denied = "~/Views/Authorize/Denied.cshtml";
            public readonly string Error = "~/Views/Authorize/Error.cshtml";
            public readonly string FBApp = "~/Views/Authorize/FBApp.cshtml";
            public readonly string Logon = "~/Views/Authorize/Logon.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AuthorizeController : RaceDay.Controllers.AuthorizeController
    {
        public T4MVC_AuthorizeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void FBAppOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult FBApp()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FBApp);
            FBAppOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LogonOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Logon()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Logon);
            LogonOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RedirectToActionWithMessageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.ActionResult redirectAction, RaceDay.PageMessageModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult RedirectToActionWithMessage(System.Web.Mvc.ActionResult redirectAction, RaceDay.PageMessageModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RedirectToActionWithMessage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "redirectAction", redirectAction);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            RedirectToActionWithMessageOverride(callInfo, redirectAction, model);
            return callInfo;
        }

        [NonAction]
        partial void AjaxRedirectOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.ActionResult redirectAction);

        [NonAction]
        public override System.Web.Mvc.ActionResult AjaxRedirect(System.Web.Mvc.ActionResult redirectAction)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AjaxRedirect);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "redirectAction", redirectAction);
            AjaxRedirectOverride(callInfo, redirectAction);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
